apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd

spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./democrm
    repoURL: 'http://3.11.200.189/Maciob/democrm.git'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
